### PR TITLE
Remove width trick to use clear rect, fix #280

### LINKED ISSUE #280: Rendering problem with Firefox
This replaces https://github.com/CartoDB/cartodb/issues/11466.

### Context
Torque visualizations don't work well in Firefox v51. 

Tiles are rendered, but for some of them are not 'cleared' and the result is similar to having the 'cumulative' option enabled. 

This happens only in Firefox, and not on every tile, as some of them work as expected. 
 

### Steps to Reproduce

1. Make sure you're using Firefox v51
2. Open this map https://team.carto.com/u/ernestomb/builder/cd37d292-ec93-11e6-9e93-0e3ebc282e83/embed
3. Check that markers are not cleared and they start accumulating, but only on some of the tiles

### Current Result

Torque maps aren't working well on Firefox

screen shot 2017-02-06 at 18 51 37

 

### Expected result

Markers should be cleared from the map 

### Browser and version

 Firefox v51

### PR DESCRIPTION
**Pull request by donflopez**
More info in #280

### CODE REVIEW

File: lib/torque/renderer/point.js [hunk 1]
```diff
@@ -89,7 +89,10 @@ var CartoDatasource = require('./datasource');
         var color = this._Map['-torque-clear-color']
         // shortcut for the default value
         if (color  === "rgba(255, 255, 255, 0)" || !color) {
-          this._canvas.width = this._canvas.width;
+          this._ctx.save();
```
Comment (dgaubert) [inline lib/torque/renderer/point.js]: Why not extract `var ctx = this._ctx;` to the main `if` and use it here?

Comment (donflopez) [inline lib/torque/renderer/point.js]: I agree, I thought about it, it was my laziness... :)
